--- #YAML:1.0
name:               Test-LongString
version:            0.14
abstract:           ~
author:
    - Rafael Garcia-Suarez <rgs@consttype.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Builder:        0.12
    Test::Builder::Tester:  1.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
